//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketPlanetEntities : DbContext
    {
        public TicketPlanetEntities()
            : base("name=TicketPlanetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admStatusItem> admStatusItems { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tk_BatchCounter> tk_BatchCounter { get; set; }
        public virtual DbSet<tk_BroadCastEmailNotifications> tk_BroadCastEmailNotifications { get; set; }
        public virtual DbSet<tk_Bus> tk_Bus { get; set; }
        public virtual DbSet<tk_BusCompany> tk_BusCompany { get; set; }
        public virtual DbSet<tk_BusType> tk_BusType { get; set; }
        public virtual DbSet<tk_Careers> tk_Careers { get; set; }
        public virtual DbSet<tk_CarriageType> tk_CarriageType { get; set; }
        public virtual DbSet<tk_Cinema> tk_Cinema { get; set; }
        public virtual DbSet<tk_Cinema_Location> tk_Cinema_Location { get; set; }
        public virtual DbSet<tk_CinemaCatgory> tk_CinemaCatgory { get; set; }
        public virtual DbSet<tk_CinemaCompany> tk_CinemaCompany { get; set; }
        public virtual DbSet<tk_CinemaPricing> tk_CinemaPricing { get; set; }
        public virtual DbSet<tk_CinemaTransactionLog> tk_CinemaTransactionLog { get; set; }
        public virtual DbSet<tk_CinemaTransactionLog_Test> tk_CinemaTransactionLog_Test { get; set; }
        public virtual DbSet<tk_CinemaTransactionLogTestEmail> tk_CinemaTransactionLogTestEmail { get; set; }
        public virtual DbSet<tk_CinemaUserProfile> tk_CinemaUserProfile { get; set; }
        public virtual DbSet<tk_ClientProfile> tk_ClientProfile { get; set; }
        public virtual DbSet<tk_ContactInformation> tk_ContactInformation { get; set; }
        public virtual DbSet<tk_CouponCodeAssignment> tk_CouponCodeAssignment { get; set; }
        public virtual DbSet<tk_Coupons> tk_Coupons { get; set; }
        public virtual DbSet<tk_CouponSetUp> tk_CouponSetUp { get; set; }
        public virtual DbSet<tk_Customers> tk_Customers { get; set; }
        public virtual DbSet<tk_DBAudit> tk_DBAudit { get; set; }
        public virtual DbSet<tk_EmailSubscription> tk_EmailSubscription { get; set; }
        public virtual DbSet<tk_EmailTemplateSetUp> tk_EmailTemplateSetUp { get; set; }
        public virtual DbSet<tk_Event> tk_Event { get; set; }
        public virtual DbSet<tk_EventCategory> tk_EventCategory { get; set; }
        public virtual DbSet<tk_EventCustomers> tk_EventCustomers { get; set; }
        public virtual DbSet<tk_EventCustomers_Test> tk_EventCustomers_Test { get; set; }
        public virtual DbSet<tk_ExtBatchCounter> tk_ExtBatchCounter { get; set; }
        public virtual DbSet<tk_ExtIntegrationProfile> tk_ExtIntegrationProfile { get; set; }
        public virtual DbSet<tk_ExtIntegrationProfile_Test> tk_ExtIntegrationProfile_Test { get; set; }
        public virtual DbSet<tk_FilmHouse_Film> tk_FilmHouse_Film { get; set; }
        public virtual DbSet<tk_FilmHouseCinemaFilms> tk_FilmHouseCinemaFilms { get; set; }
        public virtual DbSet<tk_FilmHouseMoviePerformance> tk_FilmHouseMoviePerformance { get; set; }
        public virtual DbSet<tk_Films> tk_Films { get; set; }
        public virtual DbSet<tk_Flight_Location> tk_Flight_Location { get; set; }
        public virtual DbSet<tk_FlightCompany> tk_FlightCompany { get; set; }
        public virtual DbSet<tk_FlightContactInformation> tk_FlightContactInformation { get; set; }
        public virtual DbSet<tk_FlightPassenger> tk_FlightPassenger { get; set; }
        public virtual DbSet<tk_FlightRoutes> tk_FlightRoutes { get; set; }
        public virtual DbSet<tk_FlightTransactionLog> tk_FlightTransactionLog { get; set; }
        public virtual DbSet<tk_FmToken> tk_FmToken { get; set; }
        public virtual DbSet<tk_FreeEventCustomers> tk_FreeEventCustomers { get; set; }
        public virtual DbSet<tk_FreeEvents> tk_FreeEvents { get; set; }
        public virtual DbSet<tk_GenesisFilmsAbuja> tk_GenesisFilmsAbuja { get; set; }
        public virtual DbSet<tk_GenesisFilmsAjah> tk_GenesisFilmsAjah { get; set; }
        public virtual DbSet<tk_GenesisFilmsAsaba> tk_GenesisFilmsAsaba { get; set; }
        public virtual DbSet<tk_GenesisFilmsGateway> tk_GenesisFilmsGateway { get; set; }
        public virtual DbSet<tk_GenesisFilmsMaryland> tk_GenesisFilmsMaryland { get; set; }
        public virtual DbSet<tk_GenesisFilmsOwerri> tk_GenesisFilmsOwerri { get; set; }
        public virtual DbSet<tk_GenesisFilmsWarri> tk_GenesisFilmsWarri { get; set; }
        public virtual DbSet<tk_GenesisPalmsFilms> tk_GenesisPalmsFilms { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformance> tk_GenesisPalmsPerformance { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceAbuja> tk_GenesisPalmsPerformanceAbuja { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceAjah> tk_GenesisPalmsPerformanceAjah { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceAsaba> tk_GenesisPalmsPerformanceAsaba { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceGateway> tk_GenesisPalmsPerformanceGateway { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceMaryland> tk_GenesisPalmsPerformanceMaryland { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceOwerri> tk_GenesisPalmsPerformanceOwerri { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformancePortHarcourt> tk_GenesisPalmsPerformancePortHarcourt { get; set; }
        public virtual DbSet<tk_GenesisPalmsPerformanceWarri> tk_GenesisPalmsPerformanceWarri { get; set; }
        public virtual DbSet<tk_GenesisPortHarcourt> tk_GenesisPortHarcourt { get; set; }
        public virtual DbSet<tk_Hummer15Seater> tk_Hummer15Seater { get; set; }
        public virtual DbSet<tk_LoadingImages> tk_LoadingImages { get; set; }
        public virtual DbSet<tk_LoadingImagesMobile> tk_LoadingImagesMobile { get; set; }
        public virtual DbSet<tk_Location> tk_Location { get; set; }
        public virtual DbSet<tk_Luxury51Seater> tk_Luxury51Seater { get; set; }
        public virtual DbSet<tk_Luxury59Seater> tk_Luxury59Seater { get; set; }
        public virtual DbSet<tk_MiniLuxury25Seater> tk_MiniLuxury25Seater { get; set; }
        public virtual DbSet<tk_MiniLuxury33Seater> tk_MiniLuxury33Seater { get; set; }
        public virtual DbSet<tk_MoviePerformance> tk_MoviePerformance { get; set; }
        public virtual DbSet<tk_Movies> tk_Movies { get; set; }
        public virtual DbSet<tk_Passenger> tk_Passenger { get; set; }
        public virtual DbSet<tk_PayStackRequest> tk_PayStackRequest { get; set; }
        public virtual DbSet<tk_PayStackResponse> tk_PayStackResponse { get; set; }
        public virtual DbSet<tk_PromoDayControlLog> tk_PromoDayControlLog { get; set; }
        public virtual DbSet<tk_Role> tk_Role { get; set; }
        public virtual DbSet<tk_RoleAssignment> tk_RoleAssignment { get; set; }
        public virtual DbSet<tk_Routes> tk_Routes { get; set; }
        public virtual DbSet<tk_SeatMapping> tk_SeatMapping { get; set; }
        public virtual DbSet<tk_Seina7Seater> tk_Seina7Seater { get; set; }
        public virtual DbSet<tk_ServiceSetUp> tk_ServiceSetUp { get; set; }
        public virtual DbSet<tk_SmallBusModel> tk_SmallBusModel { get; set; }
        public virtual DbSet<tk_Sms> tk_Sms { get; set; }
        public virtual DbSet<tk_TicketClass> tk_TicketClass { get; set; }
        public virtual DbSet<tk_Tickets> tk_Tickets { get; set; }
        public virtual DbSet<tk_TransactionLog> tk_TransactionLog { get; set; }
        public virtual DbSet<tk_UserLogin> tk_UserLogin { get; set; }
        public virtual DbSet<tk_UserProfile> tk_UserProfile { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<tk_CinemaTransactionLogOld> tk_CinemaTransactionLogOld { get; set; }
        public virtual DbSet<tk_MenuControl> tk_MenuControl { get; set; }
        public virtual DbSet<tk_Routes2> tk_Routes2 { get; set; }
    }
}
