//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_Bus
    {
        public int Itbid { get; set; }
        public string BusRegNo { get; set; }
        public string BusId { get; set; }
        public string BusName { get; set; }
        public string BusDescription { get; set; }
        public Nullable<int> BusType { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> SeatNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
    }
}
