//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_CinemaPricing
    {
        public int Itbid { get; set; }
        public Nullable<int> CinemaCompanyID { get; set; }
        public Nullable<int> CinemaLocation { get; set; }
        public string IsRegular2D { get; set; }
        public string IsCombo { get; set; }
        public string IsVIP2D { get; set; }
        public string Is3D { get; set; }
        public string ScreenCategory { get; set; }
        public string Description { get; set; }
        public string DayofWeek { get; set; }
        public Nullable<decimal> CutOffTimeUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> BlockBlusterUnitPrice { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
