//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_ClientProfile
    {
        public short Itbid { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string TicketPlanetCallBackUrl { get; set; }
        public string TicketPlanetFlightCallBackUrl { get; set; }
        public string TicketPlanetEventCallBackUrl { get; set; }
        public string ClientPayStackSecretKey { get; set; }
        public Nullable<short> EnforcePswdChange { get; set; }
        public Nullable<short> EnforcePswdChangeDays { get; set; }
        public Nullable<short> SessionIdleTimeout { get; set; }
        public Nullable<short> GraceLoginCount { get; set; }
        public string LoginMode { get; set; }
        public string TicketPlanetApiURL { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string MobileClientPayStackSecretKey { get; set; }
    }
}
