//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_Cinema
    {
        public int Itbid { get; set; }
        public Nullable<int> CinemaCompanyId { get; set; }
        public string CinemaName { get; set; }
        public Nullable<int> CinemaLocation { get; set; }
        public string CinemaDescription { get; set; }
        public string CinemaAddress { get; set; }
        public string ApiUrl { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public string SiteId { get; set; }
    }
}
