//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_CouponSetUp
    {
        public int Itbid { get; set; }
        public string CouponCode { get; set; }
        public string CouponCodeDesc { get; set; }
        public string CouponType { get; set; }
        public string TimeBased { get; set; }
        public Nullable<decimal> CouponValue { get; set; }
        public string CutOffTime { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
