//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_DBAudit
    {
        public System.Guid auditlogid { get; set; }
        public string Username { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> eventdateutc { get; set; }
        public string eventtype { get; set; }
        public string tablename { get; set; }
        public string recordid { get; set; }
        public string columnname { get; set; }
        public string originalvalue { get; set; }
        public string newvalue { get; set; }
    }
}
