//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_EmailTemplateSetUp
    {
        public int Itbid { get; set; }
        public string FromEmail { get; set; }
        public string Password { get; set; }
        public string TicketEmailSubject { get; set; }
        public string TicketEmailContent { get; set; }
        public string EventEmailSubject { get; set; }
        public string EventEmailContent { get; set; }
        public string BusEmailSubject { get; set; }
        public string BusEmailContent { get; set; }
        public string FreeEventEmailSubject { get; set; }
        public string FreeEventEmailContent { get; set; }
        public string EmailBroadcastContent { get; set; }
        public string EmailBroadcastSubject { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public Nullable<bool> SslRequred { get; set; }
        public Nullable<int> userId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
