//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_ExtIntegrationProfile_Test
    {
        public int Itbid { get; set; }
        public string InstitutionName { get; set; }
        public string phoneNo { get; set; }
        public string emailAddress { get; set; }
        public string accessKey { get; set; }
        public string institutionCode { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string status { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> LastAPIFetchDate { get; set; }
    }
}
