//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_FmToken
    {
        public int Itbid { get; set; }
        public string AccessCode { get; set; }
        public string Token_type { get; set; }
        public string Expires_in { get; set; }
    }
}
