//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_FilmHouseCinemaFilms
    {
        public int Itbid { get; set; }
        public string id { get; set; }
        public string title { get; set; }
        public string releaseDate { get; set; }
        public string plot { get; set; }
        public string mxfReleaseId { get; set; }
        public string MovieUrl { get; set; }
    }
}
