//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_GenesisPalmsFilms
    {
        public int Itbid { get; set; }
        public Nullable<int> CinemaId { get; set; }
        public string ShortFilmTitle { get; set; }
        public string FilmTitle { get; set; }
        public string ComingSoon { get; set; }
        public string Code { get; set; }
        public string Certificate { get; set; }
        public string Is3d { get; set; }
        public string Img_title { get; set; }
        public string Rentrak { get; set; }
        public string Youtube { get; set; }
        public string ReleaseDate { get; set; }
        public string RunningTime { get; set; }
        public string Synopsis { get; set; }
        public string Certificate_desc { get; set; }
        public string Img_1s { get; set; }
        public string Digital { get; set; }
        public string Genre { get; set; }
        public string GenreCode { get; set; }
        public string StartDate { get; set; }
        public string IMDBCode { get; set; }
        public Nullable<decimal> WeekDayPrice { get; set; }
        public Nullable<decimal> WeekDayComboPrice { get; set; }
        public Nullable<decimal> WeekDayVIPPrice { get; set; }
        public Nullable<decimal> WeekDayThreeDPrice { get; set; }
        public Nullable<decimal> WeekDayCutOffPrice { get; set; }
        public Nullable<decimal> WeekDayCutOffComboPrice { get; set; }
        public Nullable<decimal> WeekDayCutOffVipPrice { get; set; }
        public Nullable<decimal> WeekDayCutOff3D { get; set; }
        public Nullable<decimal> WeekendPrice { get; set; }
        public Nullable<decimal> WeekEndComboPrice { get; set; }
        public Nullable<decimal> WeekEndVIPPrice { get; set; }
        public Nullable<decimal> WeekEndThreeDPrice { get; set; }
        public Nullable<decimal> WeekEndCutOffPrice { get; set; }
        public Nullable<decimal> WeekEndCutOffComboPrice { get; set; }
        public Nullable<decimal> WeekEndCutOffVipPrice { get; set; }
        public Nullable<decimal> WeekEndCutOff3D { get; set; }
        public Nullable<decimal> publicHolidayPrice { get; set; }
        public Nullable<decimal> promoDayPrice { get; set; }
        public string ispromoDay { get; set; }
    }
}
