//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_GenesisPalmsPerformanceOwerri
    {
        public int Itbid { get; set; }
        public Nullable<int> CinemaId { get; set; }
        public string PerformDate { get; set; }
        public string Passes { get; set; }
        public string PerfFlags { get; set; }
        public string SoldOutLevel { get; set; }
        public string PerfCat { get; set; }
        public string DoorsOpen { get; set; }
        public string AD { get; set; }
        public string Screen { get; set; }
        public string BookingURL { get; set; }
        public string FilmCode { get; set; }
        public string SellonInternet { get; set; }
        public string TrailerTime { get; set; }
        public string WheelchairAccessible { get; set; }
        public string ReservedSeating { get; set; }
        public string SalesStopped { get; set; }
        public string PerformanceNumberSlot { get; set; }
        public string InternalBookingURLDesktop { get; set; }
        public string Code { get; set; }
        public string Subs { get; set; }
        public string PerfFlagsDescription { get; set; }
        public string ScreenCode { get; set; }
        public string StartTime { get; set; }
        public string ManagerWarningLevel { get; set; }
        public string Status { get; set; }
    }
}
