//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_LoadingImages
    {
        public int Itbid { get; set; }
        public string Slider1 { get; set; }
        public string SliderCategory { get; set; }
        public string Slider2 { get; set; }
        public string SliderCategory2 { get; set; }
        public string Slider3 { get; set; }
        public string SliderCategory3 { get; set; }
        public string Slider4 { get; set; }
        public string SliderCategory4 { get; set; }
        public string Slider5 { get; set; }
        public string SliderCategory5 { get; set; }
        public string Slider6 { get; set; }
        public string SliderCategory6 { get; set; }
        public string Slider7 { get; set; }
        public string SliderCategory7 { get; set; }
        public string TransportHeader { get; set; }
        public string HomePageBox1 { get; set; }
        public string HomePageBox1Category { get; set; }
        public string HomePageBox2 { get; set; }
        public string HomePageBox1Category2 { get; set; }
        public string HomePageBox3 { get; set; }
        public string HomePageBox1Category3 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
    }
}
