//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_Movies
    {
        public int Itbid { get; set; }
        public string MovieId { get; set; }
        public string MovieTitle { get; set; }
        public Nullable<int> MovieCategory { get; set; }
        public string MovieImageName { get; set; }
        public byte[] MovieImage { get; set; }
        public string MovieDescription { get; set; }
        public Nullable<decimal> TicketAmount { get; set; }
        public Nullable<int> CinemaId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MovieDuration { get; set; }
        public string MovieLocation { get; set; }
        public string MovieTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
