//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_MenuControl
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<short> Priority { get; set; }
        public string Status { get; set; }
        public string cssClass { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
