//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_MiniLuxury33Seater
    {
        public int Itbid { get; set; }
        public string BusColumn1 { get; set; }
        public string BusColumn2 { get; set; }
        public string BusColumn3 { get; set; }
        public string BusColumn4 { get; set; }
    }
}
