//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_PayStackRequest
    {
        public int Id { get; set; }
        public string T_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string T_S { get; set; }
        public Nullable<int> C_Id { get; set; }
        public string C { get; set; }
        public Nullable<System.DateTime> T_D { get; set; }
        public string T_R { get; set; }
        public string M_No { get; set; }
        public Nullable<int> A { get; set; }
        public string E { get; set; }
    }
}
