//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_PayStackResponse
    {
        public int Id { get; set; }
        public string Tran_Id { get; set; }
        public Nullable<int> C_Id { get; set; }
        public string TType { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
