//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_RoleAssignment
    {
        public int Itbid { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<short> CanView { get; set; }
        public Nullable<short> CanAdd { get; set; }
        public Nullable<short> CanEdit { get; set; }
        public Nullable<short> CanAuth { get; set; }
        public Nullable<short> CanDelete { get; set; }
    }
}
