//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_Routes2
    {
        public int Itbid { get; set; }
        public string RouteId { get; set; }
        public string FromRouteCode { get; set; }
        public string ToRouteCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public Nullable<System.TimeSpan> TotalTravelTime { get; set; }
        public Nullable<int> BusTypeId { get; set; }
        public Nullable<int> BusCompanyId { get; set; }
        public Nullable<int> SeatID { get; set; }
        public string CurrencyCode { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }
    }
}
