//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_SeatMapping
    {
        public int Itbid { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> CompanyTypeID { get; set; }
        public string SeatId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> SeatNo { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
    }
}
