//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_TransactionLog
    {
        public int Itbid { get; set; }
        public string ReferenceNo { get; set; }
        public string PayStackReference { get; set; }
        public string ContactFullname { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhoneNo { get; set; }
        public string ContactNextOfKinName { get; set; }
        public string ContactNextOfKinPhoneNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TripType { get; set; }
        public string FromDestination { get; set; }
        public string ToDestination { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CompanyTypeId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string SeatNo { get; set; }
        public Nullable<int> BusTypeID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string IsEmailSent { get; set; }
        public Nullable<int> Retry { get; set; }
    }
}
