//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPlanetV2.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tk_UserLogin
    {
        public System.Guid RowGuid { get; set; }
        public string Username { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> loginDate { get; set; }
        public Nullable<System.DateTime> logoutDate { get; set; }
        public string ipAddress { get; set; }
        public string macAddress { get; set; }
        public string status { get; set; }
    }
}
